administration/urls.py
from django.urls import path , include
from administration.views import Manager,Employee


urlpatterns=[
    path('', Manager.home, name='home'),
    path('manager/', include(([
                                  path('', Manager.Manager_Home, name='home'),
                                  path('changestatus/<int:type_num>/<int:status_pk>', Manager.Change_Status, name='change_status'),
                                  path('manageWork/', Manager.Work_Hours_show , name='work_hour'),
                                  path('WorkHourManage/<int:hour_num>/<int:hour_type>/<int:work_pk>', Manager.Work_Hours_manage , name='work_hour_manage'),
                                  path('reports/', Manager.reports_show , name='reports'),
                                  path('report/', Manager.report_show , name='show_report'),
                              ], 'administration'), namespace='manager')),
    path('employee/', include(([
                                   path('', Employee.Employee_Home, name='home'),
                                   path('swap/<int:pk>', Employee.Swap_Request, name='swap'),
                                   path('swapaccept/<int:pk>', Employee.Swap_Accept, name='swapaccept'),
                                   path('swaprefuse/<int:pk>', Employee.Swap_Refuse, name='swaprefuse'),
                               ], 'administration'), namespace='employee')),
]

workSystem/urls.py
from django.urls import path , include
from administration.views import Manager,Employee

urlpatterns = [
    path('', include('administration.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/' ,Manager.SignUpView.as_view() , name='signup' ),
    path('accounts/signup/manager/', Manager.ManagerSignUpView.as_view(), name='manager_signup'),
    path('accounts/signup/student/', Employee.EmployeeSignupView.as_view(), name='employee_signup'),

]

administration/forms.py
from django.contrib.auth.forms import UserCreationForm
from administration.models import User,Employee
from django.db import transaction





class ManagerSignUpForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_manager = True
        if commit:
            user.save()
        return user



class EmployeeSignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic()
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_empolyee = True
        user.save()
        employee = Employee.objects.create(user=user)
        return user

administration/views.py
from django.shortcuts import render

# Create your views here.

administration/views/Employee.py
from administration.decorators import manager_required ,employee_required
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView
from administration.models import User ,EmployeeStatus,Employee,SwapRequest
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.shortcuts import redirect
from administration.forms import EmployeeSignupForm
from django.http import HttpResponse
from django.shortcuts import render
from datetime import date
import calendar




@method_decorator([login_required,manager_required] , name='dispatch')
class EmployeeSignupView(CreateView):
    model = User
    form_class = EmployeeSignupForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'add new employee'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        form.save()
        messages.success(self.request,'Done! , Add new Employee successfully .......')
        return redirect('employee_signup')


@login_required
@employee_required
def Employee_Home(request):
    year = date.today().year
    month = date.today().month
    data=[]
    month_range=calendar.monthrange(year,month)
    for i in range(month_range[1]):
        day = date(year, month, i + 1)
        if EmployeeStatus.objects.filter(employee=request.user.employee, day=day).count() == 0:
            #     create defualt object to this employee in this day
            emp_type = EmployeeStatus.objects.create(employee=request.user.employee, day=day)
        else:
            # get the object belong to this employee
            print("pppppppppppppppppppp")
            emp_type = EmployeeStatus.objects.get(employee=request.user.employee, day=day)
            print(emp_type)
        data.append({
            'day': day,
            'day_types': emp_type
        })
    #     check if there any swap request
    swapRequest= request.user.employee.SwapRequests.filter(answer=False)
    print("======-------------------------------==========",swapRequest)

    return render(request,'work/employee/employee_home.html',{
            'data':data,
            'swaps':swapRequest
        })


@login_required
@employee_required
def Swap_Request(request,pk):
    shift = EmployeeStatus.objects.get(pk=pk)
    if not SwapRequest.objects.filter(shift = shift).count() == 0 :
        messages.info(request,"your request in progress  , please wait others employee answer")
        return redirect('employee:home')
    else:
        # check if there is employee free
        if EmployeeStatus.objects.filter(day=shift.day, type=4).count() == 0:
            messages.warning(request,"sorry threre is no employee free to take your shift")
            return redirect('employee:home')
        # collocting avalable Employee
        users_ids=[]
        for ele in EmployeeStatus.objects.filter(day=shift.day,type=4):
            users_ids.append(ele.employee.pk)
        users=Employee.objects.filter(pk__in = users_ids)
        # create swap request
        swapRequest = SwapRequest(owner=request.user.employee)
        swapRequest.shift=shift
        swapRequest.save()
        for user in users:
            swapRequest.users.add(user)
        swapRequest.save()
        messages.success(request,'you request sent successfuly , please wait the response !!! ')
        return redirect('employee:home')


@login_required
@employee_required
def Swap_Accept(request,pk):
    swap = SwapRequest.objects.get(pk=pk)
    if swap.answer :
        swap.users.remove(request.user.employee)
        swap.save()
        messages.info(request,"thank you , anther employee take this shift before you")
        return redirect("employee:home")
    else:
        myshift = EmployeeStatus.objects.get(employee=request.user.employee,day=swap.shift.day)
        myshift.type=swap.shift.type
        myshift.save()
        swap.shift.type = 6
        swap.shift.save()
        swap.answer=True
        swap.save()
        messages.success(request,"thank you , you  take this shift")
        return redirect("employee:home")




@login_required
@employee_required
def Swap_Refuse(request,pk):
    swap = SwapRequest.objects.get(pk=pk)
    swap.users.remove(request.user.employee)
    swap.save()
    return redirect("employee:home")

administration/views/Manager.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView ,CreateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from administration.decorators import manager_required
from administration.models import User
from django.contrib.auth import login
from administration.forms import ManagerSignUpForm
from django.http import HttpResponse , JsonResponse,HttpResponseRedirect
import calendar
from datetime import date
from administration.models import Employee,EmployeeStatus,workHours
from django.contrib import messages


@method_decorator([login_required,manager_required] , name='dispatch')
class SignUpView(TemplateView):
    template_name = 'registration/signup.html'



@method_decorator([login_required,manager_required] , name='dispatch')
class ManagerSignUpView(CreateView):
    model = User
    form_class = ManagerSignUpForm
    template_name = 'registration/signup_form.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'Signup as a Manager'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('signup')


def home(request):
    if request.user.is_authenticated:
        if request.user.is_empolyee:
            return redirect('employee:home')#employee home page
        else:
            return redirect('manager:home')#manager home page
    return  render(request,'work/home.html')#home pag


@login_required
@manager_required
def Manager_Home(request):
    if request.method == 'POST':
        month = (date.today().month) +1
        month_type=1
    else:
        month_type=0
        month=date.today().month
    year = date.today().year
    days=[]
    data=[]
    day_types=[]
    all_type=[]
    # collecting data with the month in work
    employees=Employee.objects.all()
    month_range=calendar.monthrange(year,month)
    for i in range(month_range[1]):
        day=date(year,month,i+1)
        # add this day to those month days
        days.append(day)
        for emp in employees:
            if EmployeeStatus.objects.filter(employee=emp,day=day).count() == 0 :
                #     create defualt object to this employee in this day
                emp_type=EmployeeStatus.objects.create(employee=emp,day=day)
            else:
                # get the object belong to this employee
                emp_type=EmployeeStatus.objects.get(employee=emp,day=day)
            # add the object to this day types
            day_types.append(emp_type)
        data.append({
            'day':day,
            'day_types':day_types
            })
        day_types=[]
        # add those day types to all type
        all_type.append(day_types)
    return render(request,'work/manager/manager_home.html',{
        'days' : days,
        'data':data,
        'all_types':all_type,
        'employees':employees,
        'month_type':month_type
    })


@login_required
@manager_required
def Change_Status(request,type_num,status_pk):
    emp = EmployeeStatus.objects.get(pk=status_pk)
    emp.type=type_num
    emp.save()
    return JsonResponse({"success": True}, status=200)


@login_required
@manager_required
def Work_Hours_show(request):
    if request.method == 'POST':
        if not request.POST['date']:
            messages.error(request,"must select date")
            return redirect('manager:home')
        day_pattern=request.POST['date'].split('-')
        if int(day_pattern[0]) != date.today().year or abs(int(day_pattern[1])-date.today().month) > 1 :
            messages.warning(request, "please select valid date")
            return redirect('manager:home')
        data=[]
        day=date(int(day_pattern[0]),int(day_pattern[1]),int(day_pattern[2]))
        shift=int(request.POST['shift'])
        Shift_hours = EmployeeStatus.objects.filter(day=day,type=shift)
        # collect the Work hours from database for each empolyee
        for ele in Shift_hours:
            if workHours.objects.filter(status=ele).count() == 0:
                #     create default object
                work_object = workHours.objects.create(status=ele)
            else:
                #        get the object existed in database
                work_object = workHours.objects.get(status=ele)
            data.append({
                'shift':ele,
                'workhour':work_object
            })

        return render(request,'work/manager/shiftworks.html',{
            'type':shift,
            'data':data
        })
    else:
        return redirect('manager:home')


@login_required
@manager_required
def Work_Hours_manage(request,hour_num,hour_type,work_pk):
    work = workHours.objects.get(pk=work_pk)
    breakNum=work.breakNum
    if breakNum == 2 and hour_type == 0:
    #     not valid
        return JsonResponse({'success':False},status=200)
    elif breakNum == 0 and hour_type ==1 :
        print("noooooooooooooooooo")
        return JsonResponse({'success':True},status=200)
    if hour_type == 0:
        if hour_num == 1:
             if work.one:
                 work.one = False
                 work.breakNum = breakNum + 1
        elif hour_num == 2:
            if work.two:
                work.two = False
                work.breakNum = breakNum + 1
        elif hour_num == 3:
            if work.three:
                work.three = False
                work.breakNum = breakNum + 1

        elif hour_num == 4:
            if work.four:
                work.four = False
                work.breakNum = breakNum + 1
        elif hour_num == 5:
            if work.five:
                work.five = False
                work.breakNum = breakNum + 1
        elif hour_num == 6:
            if work.six:
                work.six = False
                work.breakNum = breakNum + 1
        elif hour_num == 7:
            if work.seven:
                work.seven = False
                work.breakNum = breakNum + 1
        elif hour_num == 8:
            if work.eight:
                work.eight = False
                work.breakNum = breakNum + 1
    #     ============================================

    else:
        if hour_num == 1:
             if not work.one:
                 work.one = True
                 work.breakNum = breakNum - 1
        elif hour_num == 2:
            if not work.two:
                work.two = True
                work.breakNum = breakNum -1
        elif hour_num == 3:
            if not work.three:
                work.three = True
                work.breakNum = breakNum - 1

        elif hour_num == 4:
            if not work.four:
                work.four = True
                work.breakNum = breakNum - 1
        elif hour_num == 5:
            if not work.five:
                work.five = True
                work.breakNum = breakNum - 1
        elif hour_num == 6:
            if not work.six:
                work.six = True
                work.breakNum = breakNum - 1
        elif hour_num == 7:
            if not work.seven:
                work.seven = True
                work.breakNum = breakNum - 1
        elif hour_num == 8:
            if not work.eight:
                work.eight = True
                work.breakNum = breakNum - 1
    work.save()
    return JsonResponse({"success": True}, status=200)



@login_required
@manager_required
def reports_show(request):
    data=[]
    employees = Employee.objects.all()
    for emp in employees:
        data.append({
            'employee':emp,
            'hour_number':get_work_hour(emp,year = date.today().year, month = date.today().month)[0]
        })

    return render(request,'work/manager/reports.html',{
        'data':data,
        'employees':employees
    })


@login_required
@manager_required
def report_show(request):
    month=date.today().month
    year=date.today().year
    if request.method == 'POST' :
        print("==================",request.POST)
        if not request.POST['date']:
            messages.error(request,"must select date")
            return redirect('manager:reports')
        day_pattern=request.POST['date'].split('-')
        if int(day_pattern[0]) != year or abs(int(day_pattern[1])-month) > 2 :
            messages.warning(request, "please select valid date")
            return redirect('manager:reports')
        emp=Employee.objects.get(pk=request.POST['employee'])
        report=get_work_hour(emp,int(day_pattern[0]),int(day_pattern[1]))
        return render(request,'work/manager/report_show.html',{
            'hour_num':report[0],
            'break_num': report[1],
            'work_day':report[2],
            'off_day':report[3],
            'employee':emp,
            'date':f"{month} / {year}"
        })


    else:
        return redirect('home')

def get_work_hour(emp:Employee,year:int,month:int):
    month_range = calendar.monthrange(year,month)
    data=[]
    for i in range(month_range[1]):
        day= date(date.today().year,date.today().month,i+1)
        temp = EmployeeStatus.objects.get(employee=emp,day=day)
        data.append(temp)

    num = 0
    breaks = 0
    work_days = 0
    off_day = 0
    for ele in data :
        if not hasattr(ele, 'workhours'):
            workHours.objects.create(status=ele)
        if ele.type < 4:
            work_days = work_days + 1
            if ele.workhours.breakNum == 0 :
                num = num + 8
            elif ele.workhours.breakNum == 1:
                num =num +7
                breaks =breaks+1
            else:
                num = num + 6
                breaks =breaks + 2
        else:
            off_day = off_day + 1
    return [num,breaks,work_days,off_day]

administration/templates/work/manager/manager_home.html
{% extends 'base.html' %}

{% block content %}
<a class="btn btn-success text-center form-control h3" href="{%url 'signup' %}" xmlns="http://www.w3.org/1999/html"> Add New Employee</a>
    <hr>
<a class="btn btn-dark text-center form-control h3" href="{%url 'manager:reports' %}" xmlns="http://www.w3.org/1999/html"> Reports</a>
     <hr>
    <div class= "form form-control ">
            <h3 class="col-12 text-center">
                Manage Work Hours
            </h3>
        <form class="form text-center" action="{% url 'manager:work_hour' %}" method="post">
            {% csrf_token %}
            <div class="form-control">
                <label for="exampleFormControlSelect2"> Select Date</label>
                <input type="date" id="exampleFormControlSelect2" class="form-control" name="date">
            </div>
            <hr>
             <div class="form-group">
                <label for="exampleFormControlSelect1"> select Shift</label>
                <select class="form-control" id="exampleFormControlSelect1" name="shift">
                  <option value="1" >Morring</option>
                  <option value="2" >AfterNoon</option>
                  <option value="3" >Evenning</option>
                </select>
              </div>
            <input type="submit" class=" form-control text-center btn btn-primary" value="Go"></input>
        </form>
    </div>
     <hr>
    {% if month_type == 0 %}
    <div class="form form-control text-center">
            <form action="" method="post">
                {% csrf_token %}
                <input class="btn btn-info h3 form-control" type="submit" value="Show Next Month">
            </form>
    </div>
    {% else %}
    <div class="form form-control text-center">
            <form action="" method="get">
                {% csrf_token %}
                <input class="btn btn-info h3 form-control" type="submit" value="Back To prevois Month">
            </form>
    </div>
    {% endif%}
     <hr>

  <table class="table table-hover table-bordered">
        <tr class="text-center">
            <th class="table-warning">Day</th>
            {% for employee in employees %}
                <th class="table-info">
                    {{employee}}
                </th>
            {% endfor %}
        </tr>

      {% for ele in data %}
      <tr class="text-center">
          <td class=" text-center ">
              <h5>{{ele.day|date:"D"}} : {{ele.day}}</h5>
          </td>
          {% load mytags %}
          {% for type in ele.day_types %}
          {% if type.type == 1%}
            <td class="bg-warning" >
                <select class="btn btn-warning custom">
          {% elif type.type == 2 %}
            <td class="  bg-info">
                    <select class="btn btn-info custom">
          {% elif type.type == 3 %}
          <td class="  bg-danger">
                    <select class="btn btn-danger custom">
          {% elif type.type == 4 %}
            <td class="  bg-success">
                        <select class="btn btn-success custom">
          {% elif type.type == 5 %}
            <td class="  bg-primary">
                    <select class="btn btn-primary custom">
          {% elif type.type ==  6%}
            <td class=" bg-secondary">
                    <select class="btn btn-secondary custom">
          {% endif %}
                <option value="1-{{type.pk}}" {% if type.type == 1 %}selected{% endif%}>M</option>
                <option value="2-{{type.pk}}" {% if type.type == 2 %}selected{% endif%}>A</option>
                <option value="3-{{type.pk}}" {% if type.type == 3 %}selected{% endif%}>N</option>
                <option value="4-{{type.pk}}" {% if type.type == 4 %}selected{% endif%}>ON Call</option>
                <option value="5-{{type.pk}}" {% if type.type == 5 %}selected{% endif%}>Sleep</option>
                <option value="6-{{type.pk}}" {% if type.type == 6 %}selected{% endif%}>OFF Day</option>
            </select>

            </td>
          {% endfor %}

      </tr>
      {% endfor %}
  </table>
    <script type="text/javascript">
            let table = document.getElementsByTagName("table")[0],
            ajax = new XMLHttpRequest();

            table.onclick = function (event) {
            if (event.target.tagName == "SELECT") {
                console.log(event.target.value)
                num=event.target.value.split('-')
                ajax.open("GET", "http://localhost:8000/manager/changestatus/" + num[0] +"/"+num[1]);
                ajax.setRequestHeader("Access-Control-Allow-Origin", "*");
                ajax.send();
                ajax.onreadystatechange = () => {
                        if (ajax.readyState === 4 && ajax.status === 200) {
                        response = JSON.parse(ajax.responseText);
                        console.log(response);
                        if (response.success) {
                            if(num[0] == '1'){
                                event.target.classList= "btn btn-warning";
                                event.target.parentElement.classList = 'bg-warning'
                            }else if(num[0] == '2'){
                                event.target.classList= "btn btn-info";
                                event.target.parentElement.classList = 'bg-info'
                            }else if(num[0] == '3'){
                                event.target.classList="btn btn-danger";
                                event.target.parentElement.classList = 'bg-danger'
                            }else if(num[0] == '4'){
                                event.target.classList= "btn btn-success";
                                event.target.parentElement.classList = 'bg-success'
                            }else if(num[0] == '5' ){
                                event.target.classList = "btn btn-primary";
                                event.target.parentElement.classList = 'bg-primary'
                            }else{
                                event.target.classList = "btn btn-secondary";
                                event.target.parentElement.classList = 'bg-secondary'
                            }

                        } else {
                            flash.innerHTML = "<p class='alert alert-danger'>" + data.msg + "</p>";

                        }
                    }
                   }
                }
            }


    </script>
{% endblock %}

administration/templates/work/manager/report_show.html
{% extends 'base.html' %}

{% block content %}
    <div class="h2 text-center">
        <p class="">{{employee}}  :  {{date}}</p>
    </div>
    <hr>
    <table class="table text-center h3">
        <tr>
            <th class="table-info">Tobic</th>
            <th class="table-danger">Value</th>
        </tr>

        <tr>
            <td class="table-success"># of Work Hours</td>
            <td>{{hour_num}}</td>
        </tr>

        <tr>
            <td class="table-success"># of Breaks Hours</td>
            <td>{{break_num}}</td>
        </tr>

        <tr>
            <td class="table-success"># of Work Days</td>
            <td>{{work_day}}</td>
        </tr>

        <tr>
            <td class="table-success"># of OFF Days</td>
            <td>{{off_day}}</td>
        </tr>
    </table>
    <hr>
    <a class="btn btn-primary text-center form-control h3" href="{%url 'manager:reports' %}" xmlns="http://www.w3.org/1999/html"> Back</a>
    <hr>
    <a class="btn btn-danger text-center form-control h3" href="{%url 'manager:home' %}" xmlns="http://www.w3.org/1999/html"> Back To Home</a>

{% endblock %}

administration/templates/work/manager/reports.html
{% extends 'base.html' %}

{% block content %}
<script>

window.onload = function () {
        data=[]
        {% for ele in data %}
        data.push({ x: 10*{{ forloop.counter }}, y: {{ele.hour_number}}, indexLabel: "{{ele.employee }}" })
        {% endfor %}
var chart = new CanvasJS.Chart("chartContainer", {
	animationEnabled: true,
	exportEnabled: true,
	theme: "light1", // "light1", "light2", "dark1", "dark2"
	title:{
		text: "Working hours Chart"
	},
	data: [{
		type: "column", //change type to bar, line, area, pie, etc
		//indexLabel: "{y}", //Shows y value on all Data Points
		indexLabelFontColor: "#5A5757",
		indexLabelPlacement: "outside",
		dataPoints: data
	}]
});
chart.render();
document.getElementsByClassName("canvasjs-chart-credit")[0].remove()

}
</script>
<div id="chartContainer" style="height: 370px; width: 100%;"></div>
<script src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>



       <div class= "form form-control ">
            <h3 class="col-12 text-center">
                Show Spacfic Report
            </h3>
        <form class="form text-center" action="{% url 'manager:show_report' %}" method="post">
            {% csrf_token %}
            <div class="form-control">
                <label for="exampleFormControlSelect2"> Select Date</label>
                <input type="date" id="exampleFormControlSelect2" class="form-control" name="date">
            </div>
            <hr>
             <div class="form-group ">
                <label for="exampleFormControlSelect1"> select Employee</label>
                <select class="form-control" id="exampleFormControlSelect1" name="employee">
                    {% for emp in employees %}
                  <option class="text-center" value={{emp.pk}} >{{emp}}</option>
                    {% endfor %}
                </select>
              </div>
            <input type="submit" class=" form-control text-center btn btn-primary" value="Show"></input>
        </form>
    </div>
    <hr>
    <a class="btn btn-primary text-center form-control h3" href="{%url 'manager:home' %}" xmlns="http://www.w3.org/1999/html"> Back To Home</a>

{% endblock %}